#
# Makefile for the stepper motor drivers
#

obj-$(CONFIG_STEPPER) += stepper_m.o
obj-$(CONFIG_STEPPER_TMC2100) += stepper_tmc2100_m.o

stepper_m-y := stepper.o
stepper_tmc2100_m-y := tmc2100.o attributes.o
